### ISSUE TITLE
Reposition power button

### ISSUE THREAD

**Issue by Ichaelus** [Ichaelus/bitflipper#14]
The current position is visually overloaded due to its vicinity to the input selection.
We could move the button e.g. to the right.

**Comment by Ichaelus** [comment]
```css

.machine-back.-active .power-switch {
  transform: scale(1.4);
  background: #28282800;
  box-shadow: 0px 3px 0px 0px #0e0e0a, 0px 0px 6px 0px #0e0e0ac4;
  color: #7b7b7c;
  text-shadow: 0px -0.5px 9px currentColor;
  height: 36px;
  left: 861px;
  position: absolute;
  z-index: 4;
  mix-blend-mode: plus-lighter;
}

**Comment by Ichaelus** [comment]
```css
.input-visualizer {
  transform: scale(1.3);
  opacity: 09;
  // no background color
}
.machine-back.-active .power-switch {
  // no box shadow
}

```
